image: debian:latest

test:
   script:
    - apt-get update
    - apt-get -y upgrade
    - apt-get -y install libcurl4-openssl-dev libssl-dev libudunits2-dev libxml2-dev libgdal-dev libgeos-dev
    - apt-get -y install texlive gawk wget
    - apt-get -y install r-base-dev
    - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
    - dpkg -i pandoc-1.19.2.1-1-amd64.deb
    - wget https://stat.ethz.ch/R/daily/R-devel.tar.gz
    - tar -xvf R-devel.tar.gz
    - cd R-devel
    - ./configure --enable-R-shlib --enable-BLAS-shlib --with-blas --with-lapack --with-x=no # --with-readline --with-cairo --with-libtiff --with-libpng --with-jpeglib --with-blas
    - make
    - cd ..  
    - ./R-devel/bin/R -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
    - ./R-devel/bin/Rscript .gitlab-ci-r-setup.R
    - ./R-devel/bin/R CMD build --no-resave-data --md5 .
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - ./R-devel/bin/R CMD check "${PKG_FILE_NAME}"
